#include "response_code_desc.h"

namespace yuan::net::http 
{
    std::unordered_map<ResponseCode, std::string> responseCodeDescs = {
        {ResponseCode::switch_protocol, "101 Switching Protocols"},
        {ResponseCode::processing, "102 Processing"},
        {ResponseCode::ok_, "200 OK"},
        {ResponseCode::created_, "201 Created"},
        {ResponseCode::accepted, "202 Accepted"},
        {ResponseCode::no_content, "204 No Content"},
        {ResponseCode::not_modified, "304 Not Modified"},
        {ResponseCode::bad_request, "400 Bad Request"},
        {ResponseCode::partial_content, "206 Partial Content"},
        {ResponseCode::multi_status, "207 Multi-Status"},
        {ResponseCode::moved_permanently, "301 Moved Permanently"},
        {ResponseCode::found, "302 Found"},
        {ResponseCode::see_other, "303 See Other"},
        {ResponseCode::unauthorized, "401 Unauthorized"},
        {ResponseCode::method_not_allowed, "405 Method Not Allowed"},
        {ResponseCode::conflict, "409 Conflict"},
        {ResponseCode::gone, "410 Gone"},
        {ResponseCode::precondition_failed, "412 Precondition Failed"},
        {ResponseCode::payload_too_large, "413 Payload Too Large"},
        {ResponseCode::too_many_requests, "429 Too Many Requests"},
        {ResponseCode::unsupported_media_type, "415 Unsupported Media Type"},
        {ResponseCode::unprocessable_entity, "422 Unprocessable Entity"},
        {ResponseCode::locked, "423 Locked"},
        {ResponseCode::failed_dependency, "424 Failed Dependency"},
        {ResponseCode::not_found, "404 Not Found"},
        {ResponseCode::http_version_not_supported, "505 HTTP Version Not Supported"},
        {ResponseCode::not_implemented, "501 Not Implemented"},
        {ResponseCode::internal_server_error, "500 Internal Server Error"},
        {ResponseCode::service_unavailable, "503 Service Unavailable"},
        {ResponseCode::gateway_timeout, "504 Gateway Timeout"},
        {ResponseCode::bad_gateway, "502 Bad Gateway"},
        {ResponseCode::insufficient_storage, "507 Insufficient Storage"},
        {ResponseCode::forbidden, "403 Forbidden"},
    };
}
